SELECT * FROM WF_ACTIVITY
SELECT * FROM WF_ASSGN_RULE
SELECT * FROM WF_BUSINESS_PURVIEW
SELECT * FROM WF_HAVE_DONE_TASKS
SELECT * FROM WF_LOGS
SELECT * FROM WF_PRE_RULE
SELECT * FROM WF_PROCESS
SELECT * FROM WF_PROCESS_CHART
SELECT * FROM WF_ROUTING_RULE
SELECT * FROM WF_SELECT_ROUNTING
SELECT * FROM WF_SEQS
SELECT * FROM WF_TABLE_COLUMN
SELECT * FROM WF_TABLES
SELECT * FROM WF_TASK_DATA
SELECT * FROM WF_TASK_LIST
SELECT * FROM WF_TASK_PATH
SELECT * FROM WF_TODO_TASK_LIST

